[package]
name = "phyjs"
version = "0.1.0"
edition = "2021"


#rocket_contrib = "0.5.0-rc.1"
[dependencies]
rocket = "0.5.0"
[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["handlebars", "tera"]
